---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

      - name: Include all .json from defaults
        include_vars:
           dir: 'defaults'
           extensions:
               - json 

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: prod_web_services
          aws_access_key: "{{aws_access_key}}"
          aws_secret_key: "{{aws_secret_key}}"
          description: Security Group for Production Web Servers
          region: "{{ region }}"
          vpc_id: "{{vpc_id}}"
          rules:
            - proto: tcp
              from_port: "{{http}}"
              to_port: "{{http}}"
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: "{{https}}"
              to_port: "{{https}}"
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
